### ISSUE TITLE
I can not find standalone mode doc

### ISSUE THREAD

**Issue by ZhouBox** [SkywalkingTest/egg-example#1]
Sorry, when I click collector in standalone mode doc, it is 404.

**Comment by wu-sheng** [comment]
Yes, I think document link is broken. Here is the new one, https://github.com/apache/incubator-skywalking/blob/master/docs/en/setup/backend/backend-ui-setup.md#quick-start

**Comment by wu-sheng** [comment]
@ascrutae The Nodejs document needs to update.
